{{- range .Values.clusters }}
  {{- $cluster := . }}
  {{- range $i, $e := until (int $cluster.devApp) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-app-%d-%s" $cluster.name $i $.Values.spec.dev.suffix }}
  labels:
    cf.load-test: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: {{ $.Values.spec.dev.path }}
    repoURL: {{ printf "%s-%d" $.Values.spec.baseRepoUrl (mod $i 10) }}
    targetRevision: HEAD
  destination:
    name: {{ $cluster.name }}
    namespace: scale-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
---
  {{- end }}
  {{- range $i, $e := until (int $cluster.prodApp) }}
apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: {{ printf "%s-app-%d-%s" $cluster.name $i $.Values.spec.prod.suffix }}
  labels:
    cf.load-test: "true"
  finalizers:
    - resources-finalizer.argocd.argoproj.io/foreground
spec:
  project: default
  source:
    path: {{ $.Values.spec.prod.path }}
    repoURL: {{ printf "%s-app-%d" $.Values.spec.baseRepoUrl (mod $i 10) }}
    targetRevision: HEAD
  destination:
    name: {{ $cluster.name }}
    namespace: scale-test
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
      allowEmpty: true
    syncOptions:
      - PrunePropagationPolicy=foreground
      - Replace=false
      - PruneLast=false
      - Validate=true
      - CreateNamespace=true
      - ApplyOutOfSyncOnly=false
      - ServerSideApply=false
      - RespectIgnoreDifferences=false
---
  {{- end }}
{{- end }}